### Register User API
POST http://localhost:8000/api/users/signup
Content-Type: application/json
Accept: application/json

{
    "name": "randi",
    "email" : "randi2@gmail.com",
    "password": "MEssi12_",
    "password_confirmation": "MEssi12_"
}




### Login User API
POST http://localhost:8000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "email" : "randi@gmail.com",
    "password": "MEssi12_"
}



### Logout User API
POST http://localhost:8000/api/users/logout
Accept: application/json
Authorization: Bearer 18|Ihe3F5wRwoaaVpSWdZQpfRj7iuyKBaveDXGQPpg0c1b0224f



### Get Current User (Me) API
GET http://localhost:8000/api/users/me
Accept: application/json
Authorization: Bearer 20|FguzZmIVoYMrQIg1j6ziavx48ihi1bDAzenK7cUFd5709844



### Create Survey API
POST http://localhost:8000/api/survey
Content-Type: application/json
Accept: application/json
Authorization: Bearer 18|Ihe3F5wRwoaaVpSWdZQpfRj7iuyKBaveDXGQPpg0c1b0224f

{
  "title": "Lorem Ipsum",
  "description": "Deskripsi Survey",
  "expire_date": "",
  "status": true,
  "questions": [
    {
    "type": "text",
    "question": "Contoh Pertanyaan6",
    "description": "Contoh Deskripsi",
    "data": {
        "key1": "value1",
        "key2": "value2",
        "key3": "value3"
        }
    },
    {
    "type": "text",
    "question": "Contoh Pertanyaan6",
    "description": "Contoh Deskripsi",
    "data": {
        "key1": "value1",
        "key2": "value2",
        "key3": "value3"
        }
    }
  ]
}



### Get Survey API #249
GET http://localhost:8000/api/survey
Accept: application/json
Authorization: Bearer 18|Ihe3F5wRwoaaVpSWdZQpfRj7iuyKBaveDXGQPpg0c1b0224f


### Get Survey API #249
GET http://localhost:8000/api/survey/4
Accept: application/json
Authorization: Bearer 18|Ihe3F5wRwoaaVpSWdZQpfRj7iuyKBaveDXGQPpg0c1b0224f



### Update Survey API #249
PUT http://localhost:8000/api/survey/9
Content-Type: application/json
Accept: application/json
Authorization: Bearer 18|Ihe3F5wRwoaaVpSWdZQpfRj7iuyKBaveDXGQPpg0c1b0224f

{
  "title": "What000",
  "description": "what000",
  "expire_date": "",
  "status": true,
  "questions": [
    {
    "id": 5,
    "type": "text",
    "question": "Contoh Pertanyaan000",
    "description": "Contoh Deskripsi000",
    "data": {
        "key1": "value1",
        "key2": "value2",
        "key3": "value3"
        }
    },
    {
    "id": 18,
    "type": "text",
    "question": "Contoh Pertanyaan000",
    "description": "Contoh Deskripsi000",
    "data": {
        "key1": "value1",
        "key2": "value2",
        "key3": "value3"
        }
    }
  ]
}


### Delete Survey API #249
DELETE http://localhost:8000/api/survey/9
Accept: application/json
Authorization: Bearer 18|Ihe3F5wRwoaaVpSWdZQpfRj7iuyKBaveDXGQPpg0c1b0224f


### Get Survey by Slug API #249
GET http://localhost:8000/api/survey/get-by-slug/lorem-ipsum-2
Accept: application/json



### Get Survey by Title API #249
GET http://localhost:8000/api/survey/get-by-title/What
Accept: application/json



### Create Survey Answer API 
POST http://localhost:8000/api/survey/8/answer
Content-Type: application/json
Accept: application/json

{
    "answers": {
        "1": "Your answer to question 1"
    }
}


### Get Dasboard API 
GET http://localhost:8000/api/dashboard
Accept: application/json
Authorization: Bearer 22|41MT7ylM4DRgLTpx8nOh81YxNSwNojcWaxqyeikBed9a189a

