### Register User API
POST http://localhost:8000/api/users/signup
Content-Type: application/json
Accept: application/json

{
    "name": "randi",
    "email" : "randi2@gmail.com",
    "password": "MEssi12_"
    "password_confirmation": "MEssi12_"
}




### Login User API
POST http://localhost:8000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "email" : "messi@gmail.com",
    "password": "MEssi12_"
}



### Get Current User API
GET http://localhost:8000/api/users/current
Accept: application/json
Authorization: 129d9400-1adb-456a-a914-f4055b28a9d6



### Update Current User API
PATCH http://localhost:8000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 129d9400-1adb-456a-a914-f4055b28a9d6

{
    "name" : "messo"
}


### Logout User API
DELETE http://localhost:8000/api/users/logout
Accept: application/json
Authorization: 129d9400-1adb-456a-a914-f4055b28a9d6



### Create Contact API
POST http://localhost:8000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: 129d9400-1adb-456a-a914-f4055b28a9d6

{
    "first_name" : "Anjar",
    "last_name" : "",
    "email" : "anjar@gmail.com",
    "phone" : "08197643565756"
}



### Get Contact API #249
GET http://localhost:8000/api/contacts/9
Accept: application/json
Authorization: 129d9400-1adb-456a-a914-f4055b28a9d6



### Update Contact API #249
PUT http://localhost:8000/api/contacts/9
Accept: application/json
Content-Type: application/json
Authorization: 129d9400-1adb-456a-a914-f4055b28a9d6

{
    "first_name" : "Bang",
    "last_name" : "Jali juli",
    "email" : "jali@gmail.com",
    "phone" : "08197643565756"
}



### Delete Contact API #249
DELETE http://localhost:8000/api/contacts/11
Accept: application/json
Authorization: 129d9400-1adb-456a-a914-f4055b28a9d6


### Search Contact API
GET http://localhost:8000/api/contacts?email=alex
Accept: application/json
Authorization: 129d9400-1adb-456a-a914-f4055b28a9d6






### Create Address API #250
POST http://localhost:8000/api/contacts/12/addresses
Accept: application/json
Content-Type: application/json
Authorization: 129d9400-1adb-456a-a914-f4055b28a9d6

{
    "street": "Jalan Kebon Jeli",
    "city" : "Jakarta",
    "province": "DKI Jakarta",
    "country": "Indonesia",
    "postal_code": "473983"
}



### Get Address API #25
GET http://localhost:8000/api/contacts/12/addresses/2
Accept: application/json
Authorization: 129d9400-1adb-456a-a914-f4055b28a9d6


### Update Address API #25
PUT http://localhost:8000/api/contacts/12/addresses/1
Accept: application/json
Content-Type: application/json
Authorization: 129d9400-1adb-456a-a914-f4055b28a9d6

{
    "street": "Jalan Kebon Jala",
    "city" : "Jakarta",
    "province": "DKI Jakarta",
    "country": "Indonesia",
    "postal_code": "473983"
}



### Remove Address API #24
DELETE http://localhost:8000/api/contacts/12/addresses/4
Accept: application/json
Authorization: 129d9400-1adb-456a-a914-f4055b28a9d6



### List Address API
GET http://localhost:8000/api/contacts/12/addresses
Accept: application/json
Authorization: 129d9400-1adb-456a-a914-f4055b28a9d6